-- 创建 tasks 表
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT,
  time TEXT,
  priority TEXT DEFAULT 'medium',
  done BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 为匿名用户启用所有操作
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- 创建允许匿名用户读取的策略
CREATE POLICY "Enable read access for all users"
ON tasks FOR SELECT
TO anon, authenticated
USING (true);

-- 创建允许匿名用户插入的策略
CREATE POLICY "Enable insert access for all users"
ON tasks FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 创建允许匿名用户更新的策略
CREATE POLICY "Enable update access for all users"
ON tasks FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- 创建允许匿名用户删除的策略
CREATE POLICY "Enable delete access for all users"
ON tasks FOR DELETE
TO anon, authenticated
USING (true);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_tasks_done ON tasks(done);
CREATE INDEX IF NOT EXISTS idx_tasks_created_at ON tasks(created_at DESC);
